name: main
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python
    steps:
      - uses: actions/checkout@v2
      - run: wget http://newspat.csis.u-tokyo.ac.jp/download/dams-4.3.4.tgz
      - run: wget https://raw.githubusercontent.com/hottolink/pydams/master/patch/dams-4.3.4.diff
      - run: tar zxf dams-4.3.4.tgz
      - run: patch -d ./dams-4.3.4 -p1 < ./dams-4.3.4.diff
